# Generated by Django 3.2.7 on 2021-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211114_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('done_for_today', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.TextField()),
            ],
        ),
    ]
