# Generated by Django 3.2.7 on 2021-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211109_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='data_of_meeting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
