# Generated by Django 3.2.7 on 2021-11-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211112_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalformonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февральь'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрьрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=2)),
                ('difficulty', models.SmallIntegerField()),
                ('reason_for_goal', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='data_of_meeting',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
