# Generated by Django 3.2.7 on 2021-11-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211114_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goalformonth',
            new_name='goal_for_month',
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
