# Generated by Django 3.2.7 on 2021-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211114_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='data_of_meeting',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
